name: CI of mc_state_observation

on:
  push:
    paths-ignore:
      # Changes to those files don't mandate running CI
      - ".gitignore"
      - ".github/workflows/package.yaml"
      - debian/**
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  clang-format:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install clang-format-10
      run: |
        sudo apt-get -qq update
        sudo apt-get -qq install clang-format-10
    - name: Run clang-format-check
      run: |
        ./.clang-format-check.sh
  build:
    needs: clang-format
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        build-type: [RelWithDebInfo]
        compiler: [gcc, clang]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install dependencies
      uses: jrl-umi3218/github-actions/install-dependencies@master
      with:
        compiler: ${{ matrix.compiler }}
        build-type: ${{ matrix.build-type }}
        ubuntu: |
          apt: libltdl-dev libboost-all-dev doxygen doxygen-latex libmc-rtc-dev libgram-savitzky-golay-dev
          apt-mirrors:
            mc-rtc:
              cloudsmith: mc-rtc/head
        ros: |
          apt: mc-rtc-plugin tf2-eigen
    - name: Build and test
      uses: jrl-umi3218/github-actions/build-cmake-project@master
      with:
        compiler: ${{ matrix.compiler }}
        build-type: ${{ matrix.build-type }}
